[options]
;addons_path = /opt/bitnami/odoo/odoo/addons,/bitnami/odoo/addons
;admin_passwd = SaecAmtega2018
;csv_internal_sep = ,
;data_dir = /opt/bitnami/odoo/data
db_host = 192.168.33.48
db_maxconn = 64
db_name = od_bceleiro
db_password = odoo12345
db_port = 5432
;db_template = template1
db_user = bn_odoo
log_level = debug
logrotate = True
