[options]
;addons_path = /opt/bitnami/odoo/odoo/addons,/bitnami/odoo/addons
;admin_passwd = SaecAmtega2018
;csv_internal_sep = ,
;data_dir = /opt/bitnami/odoo/data
db_host = 192.168.33.31
db_maxconn = 64
db_name = od_bfederacion
db_password = odoo12345
db_port = 5433
;db_template = template1
db_user = bn_odoo
;dbfilter = od_bsubasta
;list_db=true
;debug_mode = true
;demo = {}
;dev_mode = true
;email_from = saec
log_level = debug
logrotate = True
;logfile = /opt/bitnami/odoo/logs/odoo-server.log
;pidfile = /opt/bitnami/odoo/tmp/pids/odoo.pid
;bin_path=/usr/bin
;smtp_password = 
;smtp_port = 
;smtp_server = 
;smtp_ssl = 
;smtp_user = 
